from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^list-config$', views.list_config, name='list-config'),
    url(r'^config/([0-9]+)$', views.edit_config, name='edit-config'),
    url(r'^add-config$', views.add_config, name='add-config'),
    url(r'^config/([0-9]+)/del$', views.del_config, name='del-config'),
    url(r'^config/([0-9]+)/active$', views.active_config, name='active-config'),
    url(r'^continuous-rule/([0-9]+)$', views.edit_continuous_rule, name='edit-continuous-rule'),
    url(r'^standard-rule/([0-9]+)$', views.edit_standard_rule, name='edit-standard-rule'),
    url(r'^bank-rule/([0-9]+)$', views.edit_bank_rule, name='edit-bank-rule'),
    url(r'^chase-rule/([0-9]+)$', views.edit_chase_rule, name='edit-chase-rule'),
    url(r'^config/([0-9]+)/add-continuous-rule$', views.add_continuous_rule, name='add-continuous-rule'),
    url(r'^config/([0-9]+)/add-standard-rule$', views.add_standard_rule, name='add-standard-rule'),
    url(r'^config/([0-9]+)/add-bank-rule$', views.add_bank_rule, name='add-bank-rule'),
    url(r'^config/([0-9]+)/add-chase-rule$', views.add_chase_rule, name='add-chase-rule'),
    url(r'^continuous-rule/([0-9]+)/del$', views.del_continuous_rule, name='del-continuous-rule'),
    url(r'^standard-rule/([0-9]+)/del$', views.del_standard_rule, name='del-standard-rule'),
    url(r'^bank-rule/([0-9]+)/del$', views.del_bank_rule, name='del-bank-rule'),
    url(r'^chase-rule/([0-9]+)/del$', views.del_chase_rule, name='del-chase-rule'),
    url(r'^bank-rule/([0-9]+)/add-state$', views.add_bank_rule_state, name='add-bank-rule-state'),
    url(r'^chase-rule/([0-9]+)/add-state$', views.add_chase_rule_state, name='add-chase-rule-state'),
    url(r'^bank-rule-state/([0-9]+)$', views.edit_bank_rule_state, name='edit-bank-rule-state'),
    url(r'^chase-rule-state/([0-9]+)$', views.edit_chase_rule_state, name='edit-chase-rule-state'),
    url(r'^bank-rule-state/([0-9]+)/del$', views.del_bank_rule_state, name='del-bank-rule-state'),
    url(r'^chase-rule-state/([0-9]+)/del$', views.del_chase_rule_state, name='del-chase-rule-state'),
    url(r'^standard-rule/condition/([0-9]+)/del$', views.del_standard_rule_condition, name='del-standard-rule-condition'),
    url(r'^chase-rule/condition/([0-9]+)/del$', views.del_chase_rule_condition, name='del-chase-rule-condition'),
    url(r'^bank-rule-state/condition/([0-9]+)/del$', views.del_bank_rule_state_condition, name='del-bank-rule-state-condition'),
    url(r'^chase-rule/([0-9]+)/condition/add', views.add_chase_rule_condition, name='add-chase-rule-condition'),
    url(r'^bank-rule-state/([0-9]+)/condition/add', views.add_bank_rule_state_condition, name='add-bank-rule-state-condition'),
    url(r'^standard-rule/([0-9]+)/condition/add', views.add_standard_rule_condition, name='add-standard-rule-condition'),
    url(r'^chase-rule/condition/([0-9]+)', views.edit_chase_rule_condition, name='edit-chase-rule-condition'),
    url(r'^bank-rule-state/condition/([0-9]+)', views.edit_bank_rule_state_condition, name='edit-bank-rule-state-condition'),
    url(r'^standard-rule/condition/([0-9]+)', views.edit_standard_rule_condition, name='edit-standard-rule-condition'),
]
