# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20160716_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
