# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_configuration_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_duration_beats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankRuleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.BankRule')),
            ],
        ),
        migrations.CreateModel(
            name='BankRuleStateCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_id', models.IntegerField()),
                ('inferior', models.BooleanField()),
                ('superior', models.BooleanField()),
                ('equal', models.BooleanField()),
                ('value', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.BankRuleState')),
            ],
        ),
        migrations.CreateModel(
            name='ChaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_beats', models.IntegerField()),
                ('random_states', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChaseRuleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ChaseRule')),
            ],
        ),
        migrations.CreateModel(
            name='ChaseRuleStateCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_id', models.IntegerField()),
                ('inferior', models.BooleanField()),
                ('superior', models.BooleanField()),
                ('equal', models.BooleanField()),
                ('value', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ChaseRuleState')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('midi_cc', models.IntegerField()),
                ('scale_down', models.IntegerField()),
                ('scale_up', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StandardRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('note_off', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StandardRuleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_id', models.IntegerField()),
                ('inferior', models.BooleanField()),
                ('superior', models.BooleanField()),
                ('equal', models.BooleanField()),
                ('value', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.StandardRule')),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='config',
        ),
        migrations.AddField(
            model_name='standardrule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Configuration'),
        ),
        migrations.AddField(
            model_name='continuousrule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Configuration'),
        ),
        migrations.AddField(
            model_name='chaserule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Configuration'),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Configuration'),
        ),
    ]
