# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20170623_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
