# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20170623_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousrule',
            name='param_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
