# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_continuousrule_param_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContinuousParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bankrulestatecondition',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='bankrulestatecondition',
            name='inferior',
        ),
        migrations.RemoveField(
            model_name='bankrulestatecondition',
            name='param_id',
        ),
        migrations.RemoveField(
            model_name='bankrulestatecondition',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='chaserulestatecondition',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='chaserulestatecondition',
            name='inferior',
        ),
        migrations.RemoveField(
            model_name='chaserulestatecondition',
            name='param_id',
        ),
        migrations.RemoveField(
            model_name='chaserulestatecondition',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='continuousrule',
            name='param_id',
        ),
        migrations.RemoveField(
            model_name='standardrule',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='standardrule',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='standardrule',
            name='note_off',
        ),
        migrations.RemoveField(
            model_name='standardrulecondition',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='standardrulecondition',
            name='inferior',
        ),
        migrations.RemoveField(
            model_name='standardrulecondition',
            name='param_id',
        ),
        migrations.RemoveField(
            model_name='standardrulecondition',
            name='superior',
        ),
        migrations.AddField(
            model_name='bankrulestatecondition',
            name='bool_active_on_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankrulestatecondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('=', '='), ('>', '>')], default='<', max_length=3),
        ),
        migrations.AddField(
            model_name='chaserulestatecondition',
            name='bool_active_on_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chaserulestatecondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('=', '='), ('>', '>')], default='<', max_length=3),
        ),
        migrations.AddField(
            model_name='standardrule',
            name='max_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standardrulecondition',
            name='bool_active_on_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardrulecondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('=', '='), ('>', '>')], default='<', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chaserulestatecondition',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bankrulestatecondition',
            name='bool_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AddField(
            model_name='bankrulestatecondition',
            name='continuous_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
        migrations.AddField(
            model_name='chaserule',
            name='param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.EventParam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chaserulestatecondition',
            name='bool_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AddField(
            model_name='chaserulestatecondition',
            name='continuous_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
        migrations.AddField(
            model_name='continuousrule',
            name='param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardrule',
            name='param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='config.EventParam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardrulecondition',
            name='bool_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AddField(
            model_name='standardrulecondition',
            name='continuous_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
    ]
