# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20170624_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrulestate',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
