# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_bankrulestate_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaserule',
            old_name='param',
            new_name='event_param',
        ),
        migrations.RenameField(
            model_name='chaserule',
            old_name='duration_beats',
            new_name='state_duration',
        ),
        migrations.RenameField(
            model_name='continuousrule',
            old_name='param',
            new_name='continuous_param',
        ),
        migrations.RenameField(
            model_name='standardrule',
            old_name='param',
            new_name='event_param',
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='bool_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='continuous_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chaserulestatecondition',
            name='bool_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AlterField(
            model_name='chaserulestatecondition',
            name='continuous_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
        migrations.AlterField(
            model_name='chaserulestatecondition',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='bool_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.BoolParam'),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='continuous_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.ContinuousParam'),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
