# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_auto_20170624_0649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaseRuleStateCondition',
            new_name='ChaseRuleCondition',
        ),
        migrations.AlterField(
            model_name='chaserulecondition',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ChaseRule'),
        ),
    ]
