# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20170624_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((1, 'Disco'), (2, 'Salsa'))), ('Others', ((0, 'Voices'),))], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(0, 'BPM'), (1, 'RMS Power')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chaserule',
            name='event_param',
            field=models.IntegerField(choices=[(0, 'Beat Event'), (1, 'BPM change Event'), (2, 'Gender change Event'), (3, 'Harmonic change Event')], default=0),
        ),
        migrations.AlterField(
            model_name='chaserulecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((1, 'Disco'), (2, 'Salsa'))), ('Others', ((0, 'Voices'),))], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chaserulecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(0, 'BPM'), (1, 'RMS Power')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='continuousrule',
            name='continuous_param',
            field=models.IntegerField(choices=[(0, 'BPM'), (1, 'RMS Power')], default=0),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='event_param',
            field=models.IntegerField(choices=[(0, 'Beat Event'), (1, 'BPM change Event'), (2, 'Gender change Event'), (3, 'Harmonic change Event')], default=0),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((1, 'Disco'), (2, 'Salsa'))), ('Others', ((0, 'Voices'),))], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(0, 'BPM'), (1, 'RMS Power')], default=0, null=True),
        ),
        migrations.DeleteModel(
            name='BoolParam',
        ),
        migrations.DeleteModel(
            name='ContinuousParam',
        ),
        migrations.DeleteModel(
            name='EventParam',
        ),
    ]
