# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20170625_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='active',
            field=models.BooleanField(),
        ),
    ]
