# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_auto_20170625_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankrulestatecondition',
            old_name='rule',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((2, 'Disco'), (3, 'Salsa'))), ('Others', ((1, 'Voices'),))], null=True),
        ),
        migrations.AlterField(
            model_name='bankrulestatecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(1, 'BPM'), (2, 'RMS Power')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='chaserule',
            name='event_param',
            field=models.IntegerField(choices=[(1, 'Beat'), (2, 'BPM change'), (3, 'Gender change'), (4, 'Harmonic change')], default=1),
        ),
        migrations.AlterField(
            model_name='chaserulecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((2, 'Disco'), (3, 'Salsa'))), ('Others', ((1, 'Voices'),))], null=True),
        ),
        migrations.AlterField(
            model_name='chaserulecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(1, 'BPM'), (2, 'RMS Power')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='continuousrule',
            name='continuous_param',
            field=models.IntegerField(choices=[(1, 'BPM'), (2, 'RMS Power')], default=1),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='event_param',
            field=models.IntegerField(choices=[(1, 'Beat'), (2, 'BPM change'), (3, 'Gender change'), (4, 'Harmonic change')], default=1),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='bool_param',
            field=models.IntegerField(blank=True, choices=[('Genders', ((2, 'Disco'), (3, 'Salsa'))), ('Others', ((1, 'Voices'),))], null=True),
        ),
        migrations.AlterField(
            model_name='standardrulecondition',
            name='continuous_param',
            field=models.IntegerField(blank=True, choices=[(1, 'BPM'), (2, 'RMS Power')], default=1, null=True),
        ),
    ]
